server:
    port: 8080
custom:
    base:
        rate: 8
    insurance:
        percentage: 10
        rate:
            reduction: 3
    salary:
        rate:
            reduction: 1
    text:
        invalidValue: "Invalid value"
        nonNull: "Should not be null"
